services:
  db:
    image: mariadb:10.11
    container_name: japanese_learning_db
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: japanese_learning_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: japanese_learning_api
    env_file:
      - .env
    environment:
      # Bắt buộc phải có biến môi trường này vì dự án đã xóa profile mặc định
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/japanese_learning_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
