server:
  port: 8080

spring:
  application:
    name: japanese-learning-api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

# Common App properties
app:
  admin:
    email: admin@example.com
  frontend-url: http://localhost:5173
  backend-url: http://localhost:8080

# Common JWT properties
jwt:
  expiration:
    access: 900000 # 15 minutes in ms
    refresh: 604800000 # 7 days in ms
